const jwtMiddleWare = require('../MiddleWare/checkActiveUser');
const express = require('express');
const register = require('../Controller/registration');
const loginForm = require('../Controller/loginForm');
const login = require('../Controller/login');
const deshboard = require('../Controller/deshboard');
const insertUser = require('../Controller/insertUser');
const welcomeUser = require('../Controller/welcome');
const forgotPass = require('../Controller/forgotPass');
const logOut = require('../Controller/logOut');
const regeneratePass = require('../Controller/regeneratePass');
const tictactoe = require('../Controller/jsAssignments/ticTacToe');
const dyTable = require('../Controller/jsAssignments/dyTable');
const kukuCube = require('../Controller/jsAssignments/kookuCube');
const ehya = require('../Controller/htmlAssignments/ehya');
const awan = require('../Controller/htmlAssignments/awan');
const HireX = require('../Controller/htmlAssignments/hireX');
const JobAppForm = require('../Controller/htmlAssignments/jobAppForm');
const fetchApi = require('../Controller/nodeJsAssignments/jsonPlaceholderAPI/fetchApi');
const singlePost = require('../Controller/nodeJsAssignments/jsonPlaceholderAPI/singlePost');
const attendence = require('../Controller/nodeJsAssignments/attendence');
const pagination = require('../Controller/nodeJsAssignments/pagination');
const dycomponent = require('../Controller/nodeJsAssignments/components');
const delimeterSearch = require('../Controller/nodeJsAssignments/delimeterSearch');
const renderForm = require('../Controller/nodeJsAssignments/crudOps/renderForm');
const insertData = require('../Controller/nodeJsAssignments/crudOps/insertData');
const fetchdata = require('../Controller/nodeJsAssignments/crudOps/fetchData');
const crudAjax = require('../Controller/nodeJsAssignments/crudAjax/renderForm');
const insertAjax = require('../Controller/nodeJsAssignments/crudAjax/insertdata');
const fetchAjax = require('../Controller/nodeJsAssignments/crudAjax/fetchdata');
const updateAjax = require('../Controller/nodeJsAssignments/crudAjax/updatedata');


const router = express.Router();
router.get('/', loginForm);
router.get('/register', register);
router.post('/insert', insertUser);
router.get('/welcome/:key', welcomeUser);
router.post('/login', login);
router.get('/forgotPass', forgotPass);
router.get('/regeneratePass', regeneratePass);
router.get('/deshboard', jwtMiddleWare, deshboard);
router.get('/tic_tac_toe', tictactoe);
router.get('/DyTable', dyTable);
router.get('/kukuCube', kukuCube);
router.get('/ehya', ehya);
router.get('/AwanHoster', awan);
router.get('/HireX', HireX);
router.get('/JobAppForm', JobAppForm);
router.get('/FetchAPI', fetchApi);
router.get('/singlepost/:id', singlePost);
router.get('/Attendence', attendence);
router.get('/Pagination', pagination);
router.get('/DyComponent', dycomponent);
router.get('/delimeterSearch', delimeterSearch);
router.get('/Crud', renderForm);
router.post('/insertdata', insertData);
router.get('/edit', fetchdata);
router.get('/CurdAjax', crudAjax);
router.post('/insertAjax', insertAjax);
router.get('/editAjax/:id', fetchAjax);
router.post('/update', updateAjax);
router.get('/logout', logOut);

module.exports = router;